--  1. The Total revenue generated by the company for each product category.

SELECT category, SUM(s.amount) AS total_amount
FROM apnibus.sales s
JOIN apnibus.product p ON s.product_id = p.product_id
group by p.category;


-- 2. TOP PURCHASERS - Top 5 customers who have made the highest total purchases, considering the customer's age and gender.

SELECT c.customer_id, c.age, c.gender, SUM(s.amount) AS total_purchases
FROM sales s
JOIN customer c ON s.customer_id = c.customer_id
GROUP BY c.customer_id, c.age, c.gender
ORDER BY total_purchases DESC
LIMIT 5;


-- 3. Most profitable product category by calculating the average revenue per unit sold.

select * from product;
select * from sales;

SELECT AVG(s.amount/ s.quantity) AS avg_revenue_per_unit, p.category
FROM sales s
JOIN product p ON s.product_id = p.product_id
group by p.category
order by avg_revenue_per_unit;


-- 4. Analyze the inventory data and identify products that need restocking (stock count less than a specified threshold).

select product.product_id, inventory.stock_count from inventory
where inventory.stock_count < 500;


-- 5. Write a SQL query to calculate the average age of customers for each product category.

-- First we joined customer table and sales table with customer_id of customer and sales table
-- then we joined that table with product table using product_id of product and sales table. 
-- Using select statement, we retrived product category and average age of customers as output.
 
select product.category, avg(age) as 'Average Age'
from customer
join sales
on customer.customer_id = sales.customer_id
join product
on product.product_id = sales.product_id
group by product.category;


-- 6. Write a SQL query to retrieve the top 3 product categories that have the highest average transaction amount.

-- Since This dataset has only 3 categories, I will find the top 2 categories

select product.category
from product
join sales
on product.product_id = sales.product_id
group by product.category
order by avg(sales.amount)
limit 2;
